-- DOST System Database Schema — PostgreSQL version (for Supabase)
-- Converted from dost_system_schema.sql (MySQL) for CI4 "Postgre" driver.
-- Column names are double-quoted to preserve the camelCase names the app uses.
-- Run this in the Supabase SQL Editor (Database -> SQL Editor -> paste -> Run).

-- ==========================================
-- Main Tables
-- ==========================================

-- Projects Table (Core Project Data)
CREATE TABLE "projects_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "projectCode" VARCHAR(200),
    "programCode" VARCHAR(200),
    "ISP" VARCHAR(200),
    "programTitle" TEXT,
    "projectTitle" TEXT,
    "responsiblePerson" VARCHAR(200),
    "funding" VARCHAR(200),
    "implementingAgency" VARCHAR(200),
    "programLeader" VARCHAR(200),
    "projectLeader" VARCHAR(200),
    "emailAddress" VARCHAR(200),
    "contactNumber" VARCHAR(200),
    "postalAddress" VARCHAR(200),
    "cooperatingAgency" VARCHAR(200),
    "originalStart" VARCHAR(200),
    "originalEnd" VARCHAR(200),
    "changeStart" VARCHAR(200),
    "changeImplementationDate" VARCHAR(200),
    "firstExtension" VARCHAR(200),
    "secondExtension" VARCHAR(200),
    "objectives" TEXT,
    "description" TEXT,
    "deliverables" TEXT,
    "beneficiaries" TEXT,
    "status" VARCHAR(200),
    "remarks" VARCHAR(200),
    "projectAccomplishment" TEXT,
    "dcY1Approval" VARCHAR(200),
    "gcY1Approval" VARCHAR(200),
    "execomY1Approval" VARCHAR(200),
    "dcY2Renewal" VARCHAR(200),
    "gcY2Renewal" VARCHAR(200),
    "execomY2Renewal" VARCHAR(200),
    "dcY3Renewal" VARCHAR(200),
    "gcY3Renewal" VARCHAR(200),
    "execomY3Renewal" VARCHAR(200),
    "inceptionMeeting" VARCHAR(200),
    "mande" VARCHAR(200),
    "y1BudgetRealignment" VARCHAR(200),
    "y2BudgetRealignment" VARCHAR(200),
    "y3BudgetRealignment" VARCHAR(200),
    "programReview" VARCHAR(200),
    "terminalReview" VARCHAR(200),
    "submissionTerminal" VARCHAR(200),
    "created_by" VARCHAR(200),
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200)
);

-- Proposals Table
CREATE TABLE "proposals_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ISP" VARCHAR(200),
    "programTitle" TEXT,
    "projectTitle" TEXT,
    "responsiblePerson" TEXT,
    "implementingAgency" VARCHAR(200),
    "programLeader" VARCHAR(200),
    "leadTRD" VARCHAR(200),
    "funding" VARCHAR(200),
    "quarter" VARCHAR(200),
    "date" VARCHAR(200),
    "remarks" VARCHAR(200),
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200)
);

-- Budget Table
CREATE TABLE "budget_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id" INTEGER,
    "year" INTEGER,
    "amount" DECIMAL(12,2),
    "totalBudget" DECIMAL(12,2),
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200),
    FOREIGN KEY ("project_id") REFERENCES "projects_tbl"("id")
);

-- User Table
CREATE TABLE "user" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "first_name" VARCHAR(200),
    "last_name" VARCHAR(200),
    "password" VARCHAR(200),
    "email" VARCHAR(200),
    "user_lvl" VARCHAR(200),
    "reset_token" VARCHAR(200),
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200)
);

-- Sample user accounts (imported from existing dump)
-- Passwords are bcrypt hashes (password_hash/PASSWORD_DEFAULT).
-- Plaintext equivalents: admin, sample, mike1, 1234566, Test123456
INSERT INTO "user" ("id", "first_name", "last_name", "password", "email", "user_lvl", "reset_token", "created_at", "updated_at", "deleted_at") VALUES
(1, 'Joshua', 'Barte', '$2y$10$HqUW8H0MHBk0EnQqgHovu.U69njhStKKw3rrornrBMg3KgSr1HiNS', 'bartejoshua190@gmail.com', '0', '', '2024-05-09 09:29:55', '2024-05-14 12:03:24', ''),
(2, 'sample', 'sample', '$2y$10$PWoIIj1cGT16c0gdKhDaCOtbF/QOENlHo4d6egkL08Fvws7/8p8U.', 'sample@gmail.com', '1', '', '2024-05-15 09:58:24', '2024-05-15 09:59:53', ''),
(4, 'Mike', 'Zayas', '$2y$10$QEQ3saVstHDdk6jNr1Ui1uNLO4Vs7kYSaM30yvI4MIp.nwpq69E2.', 'mike1@gmail.com', '1', '', '2026-05-25 19:51:51', '2026-05-25 20:00:17', ''),
(6, 'Justine', 'Suiza', '$2y$10$/OYxOmB2fvfIvkUGuJf/JeFa5VzzzmpHR.FlJAoBoUTqOKy8LfZYK', 'justinesuiza1@gmail.com', '1', '', '2026-05-25 20:02:43', '2026-05-25 20:03:06', ''),
(7, 'Test', 'User', '$2y$10$Y8vfshaES07o9gDl7nCtDOr8wpzZrM3NShb.i2RzDSs67VYv8s84m', 'test@test.com', '2', '', '2026-06-04 09:23:06', '2026-06-04 09:23:06', '');

-- Advance the user.id sequence past the explicit ids above
SELECT setval(pg_get_serial_sequence('"user"', 'id'), (SELECT max("id") FROM "user"), true);

-- Releases Table
CREATE TABLE "releases_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id" INTEGER,
    "programmedAmount" DECIMAL(12,2),
    "regionIA" VARCHAR(200),
    "particulars" VARCHAR(200),
    "dvNo" VARCHAR(200),
    "dateOfRelease" VARCHAR(200),
    "month" VARCHAR(200),
    "actualRelease" DECIMAL(12,2),
    "remarksReleases" VARCHAR(200),
    "statusReleases" VARCHAR(200),
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200),
    FOREIGN KEY ("project_id") REFERENCES "projects_tbl"("id")
);

-- Counterpart Fund Table
CREATE TABLE "counterpartFund_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id" INTEGER,
    "year" INTEGER,
    "amount" DECIMAL(12,2),
    "totalFund" DECIMAL(12,2),
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200),
    FOREIGN KEY ("project_id") REFERENCES "projects_tbl"("id")
);

-- Gaps Table
CREATE TABLE "gaps_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id" INTEGER DEFAULT NULL,
    "phase" VARCHAR(200),
    "hatchery" TEXT,
    "nursery" TEXT,
    "growOut" TEXT,
    "postHarvest" TEXT,
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200),
    FOREIGN KEY ("project_id") REFERENCES "projects_tbl"("id")
);

-- Files Upload Table
CREATE TABLE "files_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id" INTEGER,
    "implementationFilename" VARCHAR(200),
    "implementationFilepath" VARCHAR(200),
    "extensionFilename" VARCHAR(200),
    "extensionFilepath" VARCHAR(200),
    "realignmentFilename" VARCHAR(200),
    "realignmentFilepath" VARCHAR(200),
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200),
    FOREIGN KEY ("project_id") REFERENCES "projects_tbl"("id")
);

-- 6PS Performance Table
CREATE TABLE "sixPS_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id" INTEGER,
    "year" INTEGER,
    "targetPublication" TEXT,
    "actualaccomplishmentPeer" TEXT,
    "actualaccomplishmentJournal" TEXT,
    "actualaccomplishmentPresented" TEXT,
    "details" TEXT,
    "actualaccomplishmentIEC" TEXT,
    "targetProduct" TEXT,
    "techName" TEXT,
    "techDescription" TEXT,
    "targetPatent" TEXT,
    "agency" TEXT,
    "techNamePro" TEXT,
    "statusSix" TEXT,
    "dost" TEXT,
    "patentNumber" TEXT,
    "targetPeople" TEXT,
    "namesBS" TEXT,
    "namesMS" TEXT,
    "namesPhD" TEXT,
    "targetPlaces" TEXT,
    "cooperators" TEXT,
    "international" TEXT,
    "privateSixPS" TEXT,
    "targetPolicy" TEXT,
    "policyRecommendation" TEXT,
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200),
    FOREIGN KEY ("project_id") REFERENCES "projects_tbl"("id")
);

-- Future S&T Directions Table
CREATE TABLE "future_sandt_directions_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "industrySituation" TEXT,
    "goals" TEXT,
    "bannerProgram" VARCHAR(255),
    "programProject" TEXT,
    "year" INTEGER,
    "budget" VARCHAR(255),
    "pillar" VARCHAR(255),
    "strategy" TEXT,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "deleted_at" TIMESTAMP
);

-- Indirect Cost Summary Table
CREATE TABLE "indirect_cost_summary_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "item" VARCHAR(500) NOT NULL,
    "totalReleases" DECIMAL(15,2) DEFAULT 0,
    "totalObligation" DECIMAL(15,2) DEFAULT 0,
    "runningBalance" DECIMAL(15,2) DEFAULT 0,
    "forPayment" DECIMAL(15,2) DEFAULT 0,
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200)
);

-- Disbursement Voucher Table (detailed)
CREATE TABLE "disbursement_voucher_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "indirect_cost_id" INTEGER NOT NULL,
    "project_id" INTEGER DEFAULT NULL,
    "dv_number" VARCHAR(200),
    "dv_date" TIMESTAMP DEFAULT NULL,
    "reference_no" VARCHAR(200) DEFAULT NULL,
    "payee" VARCHAR(200) DEFAULT NULL,
    "item_description" TEXT DEFAULT NULL,
    "amount" DECIMAL(15,2) DEFAULT 0,
    "status" VARCHAR(100) DEFAULT 'draft',
    "prepared_by" VARCHAR(200) DEFAULT NULL,
    "approved_by" VARCHAR(200) DEFAULT NULL,
    "created_at" TIMESTAMP DEFAULT NULL,
    "updated_at" TIMESTAMP DEFAULT NULL,
    "deleted_at" TIMESTAMP DEFAULT NULL,
    FOREIGN KEY ("indirect_cost_id") REFERENCES "indirect_cost_summary_tbl"("id") ON DELETE CASCADE,
    FOREIGN KEY ("project_id") REFERENCES "projects_tbl"("id") ON DELETE SET NULL
);

-- Indexes for voucher search
CREATE INDEX idx_voucher_dv_number ON "disbursement_voucher_tbl"("dv_number");
CREATE INDEX idx_voucher_project ON "disbursement_voucher_tbl"("project_id");

-- ==========================================
-- Archive Tables (Historical Records)
-- ==========================================

-- Archive Projects Table
CREATE TABLE "archive_projects_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ISP" VARCHAR(200),
    "programTitle" TEXT,
    "projectTitle" TEXT,
    "responsiblePerson" VARCHAR(200),
    "funding" VARCHAR(200),
    "implementingAgency" VARCHAR(200),
    "programLeader" VARCHAR(200),
    "emailAddress" VARCHAR(200),
    "contactNumber" VARCHAR(200),
    "postalAddress" VARCHAR(200),
    "cooperatingAgency" VARCHAR(200),
    "originalStart" VARCHAR(200),
    "originalEnd" VARCHAR(200),
    "changeStart" VARCHAR(200),
    "changeImplementationDate" VARCHAR(200),
    "firstExtension" VARCHAR(200),
    "secondExtension" VARCHAR(200),
    "objectives" TEXT,
    "description" TEXT,
    "deliverables" TEXT,
    "beneficiaries" TEXT,
    "status" VARCHAR(200),
    "remarks" VARCHAR(200),
    "dcY1Approval" VARCHAR(200),
    "gcY1Approval" VARCHAR(200),
    "execomY1Approval" VARCHAR(200),
    "dcY2Renewal" VARCHAR(200),
    "gcY2Renewal" VARCHAR(200),
    "execomY2Renewal" VARCHAR(200),
    "dcY3Renewal" VARCHAR(200),
    "gcY3Renewal" VARCHAR(200),
    "execomY3Renewal" VARCHAR(200),
    "inceptionMeeting" VARCHAR(200),
    "mande" VARCHAR(200),
    "y1BudgetRealignment" VARCHAR(200),
    "y2BudgetRealignment" VARCHAR(200),
    "y3BudgetRealignment" VARCHAR(200),
    "programReview" VARCHAR(200),
    "terminalReview" VARCHAR(200),
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200)
);

-- Archive Proposals Table
CREATE TABLE "archive_proposals_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ISP" VARCHAR(200),
    "programTitle" TEXT,
    "projectTitle" TEXT,
    "responsiblePerson" VARCHAR(200),
    "implementingAgency" VARCHAR(200),
    "leadTRD" VARCHAR(200),
    "funding" VARCHAR(200),
    "quarter" VARCHAR(200),
    "date" VARCHAR(200),
    "remarks" VARCHAR(200),
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200)
);

-- Archive Budget Table
CREATE TABLE "archive_budget_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id" INTEGER,
    "year" INTEGER,
    "amount" DECIMAL(10,2),
    "totalBudget" DECIMAL(10,2),
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200),
    FOREIGN KEY ("project_id") REFERENCES "archive_projects_tbl"("id")
);

-- Archive Releases Table
CREATE TABLE "archive_releases_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id" INTEGER,
    "programmedAmount" DECIMAL(10,2),
    "regionIA" VARCHAR(200),
    "particulars" VARCHAR(200),
    "dvNo" VARCHAR(200),
    "dateOfRelease" VARCHAR(200),
    "month" VARCHAR(200),
    "actualRelease" VARCHAR(200),
    "remarksReleases" VARCHAR(200),
    "statusReleases" VARCHAR(200),
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200),
    FOREIGN KEY ("project_id") REFERENCES "archive_projects_tbl"("id")
);

-- Archive Counterpart Fund Table
CREATE TABLE "archive_counterpartFund_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id" INTEGER,
    "year" INTEGER,
    "amount" DECIMAL(10,2),
    "totalFund" DECIMAL(10,2),
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200),
    FOREIGN KEY ("project_id") REFERENCES "archive_projects_tbl"("id")
);

-- ==========================================
-- Indexes for Performance
-- ==========================================

CREATE INDEX idx_projects_status ON "projects_tbl"("status");
CREATE INDEX idx_projects_isp ON "projects_tbl"("ISP");
CREATE INDEX idx_projects_funding ON "projects_tbl"("funding");
CREATE INDEX idx_budget_project ON "budget_tbl"("project_id");
CREATE INDEX idx_budget_year ON "budget_tbl"("year");
CREATE INDEX idx_releases_project ON "releases_tbl"("project_id");
CREATE INDEX idx_releases_month ON "releases_tbl"("month");
CREATE INDEX idx_counterpart_project ON "counterpartFund_tbl"("project_id");
CREATE INDEX idx_counterpart_year ON "counterpartFund_tbl"("year");
CREATE INDEX idx_sixps_project ON "sixPS_tbl"("project_id");
CREATE INDEX idx_sixps_year ON "sixPS_tbl"("year");
CREATE INDEX idx_user_email ON "user"("email");

-- ==========================================
-- Proposal Type Tables
-- Separate tables for Concept, Fullblown, and IDD Proposals
-- ==========================================

CREATE TABLE "concept_proposals_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id" INTEGER DEFAULT NULL,
    "ISP" VARCHAR(200),
    "programTitle" TEXT,
    "projectTitle" TEXT,
    "responsiblePerson" VARCHAR(200),
    "implementingAgency" VARCHAR(200),
    "programLeader" VARCHAR(200),
    "leadTRD" VARCHAR(200),
    "funding" VARCHAR(200),
    "quarter" VARCHAR(50),
    "proposal_date" VARCHAR(200),
    "proposal_file" VARCHAR(255),
    "status" VARCHAR(100),
    "remarks" VARCHAR(200),
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200),
    FOREIGN KEY ("project_id") REFERENCES "projects_tbl"("id") ON DELETE SET NULL
);

CREATE TABLE "fullblown_proposals_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id" INTEGER DEFAULT NULL,
    "ISP" VARCHAR(200),
    "programTitle" TEXT,
    "projectTitle" TEXT,
    "responsiblePerson" VARCHAR(200),
    "implementingAgency" VARCHAR(200),
    "programLeader" VARCHAR(200),
    "leadTRD" VARCHAR(200),
    "funding" VARCHAR(200),
    "quarter" VARCHAR(50),
    "proposal_date" VARCHAR(200),
    "proposal_file" VARCHAR(255),
    "status" VARCHAR(100),
    "remarks" VARCHAR(200),
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200),
    FOREIGN KEY ("project_id") REFERENCES "projects_tbl"("id") ON DELETE SET NULL
);

CREATE TABLE "idd_proposals_tbl" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id" INTEGER DEFAULT NULL,
    "ISP" VARCHAR(200),
    "programTitle" TEXT,
    "projectTitle" TEXT,
    "responsiblePerson" VARCHAR(200),
    "implementingAgency" VARCHAR(200),
    "programLeader" VARCHAR(200),
    "leadTRD" VARCHAR(200),
    "funding" VARCHAR(200),
    "quarter" VARCHAR(50),
    "proposal_date" VARCHAR(200),
    "proposal_file" VARCHAR(255),
    "status" VARCHAR(100),
    "remarks" VARCHAR(200),
    "created_at" VARCHAR(200),
    "updated_at" VARCHAR(200),
    "deleted_at" VARCHAR(200),
    FOREIGN KEY ("project_id") REFERENCES "projects_tbl"("id") ON DELETE SET NULL
);

-- Indexes for the new proposal tables
CREATE INDEX idx_concept_proposals_project ON "concept_proposals_tbl"("project_id");
CREATE INDEX idx_fullblown_proposals_project ON "fullblown_proposals_tbl"("project_id");
CREATE INDEX idx_idd_proposals_project ON "idd_proposals_tbl"("project_id");

-- ==========================================
-- Row Level Security
-- Blocks Supabase's public anon key (no policies = no access).
-- The PHP backend connects as "postgres", which bypasses RLS, so the app is unaffected.
-- Do NOT add FORCE ROW LEVEL SECURITY — that would also block the postgres superuser.
-- ==========================================
DO $$
DECLARE t text;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public'
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;